### ISSUE TITLE
datefile appender memory leak

### ISSUE THREAD

**Issue by xinyue503** [nomiddlename/log4js-node#338] opened 2015-11-30 08:20 UTC
My configuration：
log4js.configure({
    appenders: [
        {
            type: 'console',
            category: "console"
        }, //控制台输出
        {
            type: "dateFile",
            filename: serconf.logPath + 'log4jstest.log',
            pattern: "_yyyy-MM-dd",
            alwaysIncludePattern: false,
            category: 'dateFileLog'
        }//日期文件格式
    ],
    replaceConsole: true,   //INFO,DEBUG,ERROR,WARN
    levels:{
        dateFileLog: 'DEBUG'
    }
});

the program Use jmeter to conduct stress tests 1000 threads, running for an hour, hang up

How should handle?

**Comment by royalrover** [comment] 2016-08-12 04:00
I have the same question.
I analyse the heapdump, and find lots of "writeableState" & "DateRollingFileStream" Object. These Objects costs 90% of mem。

**Comment by nomiddlename** [comment] 2016-11-09 21:41
I've tried reproducing this with the following script:
```javascript
var log4js = require('../lib/log4js');
log4js.configure({
  appenders: [
    {
      type: 'console',
      category: "console"
    }, //控制台输出
    {
      type: "dateFile",
      filename: 'log4jstest.log',
      pattern: "_yyyy-MM-dd",
      alwaysIncludePattern: false,
      category: 'dateFileLog'
    }//日期文件格式
  ],
  replaceConsole: true, //INFO,DEBUG,ERROR,WARN
  levels:{
    dateFileLog: 'DEBUG'
  }
});
var logger = log4js.getLogger('dateFileLog');
// log every 30ms
var tid = setInterval(function () {
  logger.debug("cheese and crackers");
  console.log('some other logging thing.');
}, 10);

// stop after 30s
setTimeout(function() {
  clearInterval(tid);
}, 30000);
```
The only memory leak I see when profiling is the known issue with the console appender. If you replace the console appender with `stdout` appender, then the memory allocation is pretty flat. If you can give me any more information, or even better some code that reproduces the issue, that would be great.

**Comment by nomiddlename** [comment] 2016-12-13 21:13
Closing this issue because I can't reproduce. Happy to look at it again in future, if there is a way of reproducing the problem.

**Closed by nomiddlename** 2016-12-13 21:13 UTC

**Comment by davidvivi** [comment] 2020-11-11 10:03
> Closing this issue because I can't reproduce. Happy to look at it again in future, if there is a way of reproducing the problem.
I reproduce it,
![image](https://user-images.githubusercontent.com/19609057/98797842-13996f80-2448-11eb-92a0-74700b92f8da.png)

**Comment by davidvivi** [comment] 2020-11-11 10:07
@nomiddlename I reproduce it,
![Uploading image.png…]()

**Comment by joelrich** [comment] 2020-11-24 09:48
@davidvivi What is the exact behavior? I am observing a memory issue in my application which happens (but only sometimes) right after midnight. Before that it's fine. Is it the same for you or does the memory consumption increase right after starting? Have you enabled gzip compression? Do you use daily or hourly rolling? This is my configuration:

```
        _traceFile: {type: 'dateFile', filename: `${logDir}/trace.log`, layout: layout, daysToKeep: 7, compress: true},
```

(Just to be clear here: I don't have proof yet this is really due to log4js)
