### ISSUE TITLE
fileAppender write after end, 

### ISSUE THREAD

**Issue by leegee** [nomiddlename/log4js-node#385] opened 2016-05-04 12:43 UTC
Log4js-node: `"version": "0.6.35"`

[package.json.txt](https://github.com/nomiddlename/log4js-node/files/248730/package.json.txt)

Circumstance: with a large log file, or any empty log file.

Configuration:

``` json
{
    "appenders": [
        {
            "type": "categoryFilter",
            "exclude": [],
            "appender": {
                "type": "console",
                "layout": {
                    "type": "pattern",
                    "pattern": "%[%-10c %-5p%] %m"
                }
            }
        },
        {
          "type": "file",
          "filename": "temp.log",
          "maxLogSize": 20480,
          "layout": {
             "type": "pattern",
             "pattern": "%[%-10c %-5p%] %m"
          }
        }
    ],
    "replaceConsole": true
}
```

Output (repeated many, many times):

```
[31mconsole    ERROR[39m log4js.fileAppender - Writing to file temp.log, error happened  [Error: write after end]
Error: write after end
    at writeAfterEnd (_stream_writable.js:159:12)
    at RollingFileStream.Writable.write (_stream_writable.js:204:5)
    at Logger.<anonymous> (D:\src\thin-monitor2\node_modules\log4js\lib\appenders\file.js:68:13)
    at emitOne (events.js:82:20)
    at Logger.emit (events.js:169:7)
    at Logger._log (D:\src\thin-monitor2\node_modules\log4js\lib\logger.js:91:8)
    at Logger.(anonymous function) [as info] (D:\src\thin-monitor2\node_modules\log4js\lib\logger.js:83:14)
    at Console.log (D:\src\thin-monitor2\node_modules\log4js\lib\log4js.js:359:10)
    at Object.puts (C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\built\logger.js:24:17)
    at log_ (C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\built\launcher.js:24:12)
```

Followed by:

```
RangeError: Maximum call stack size exceeded
    at Function.getOwnPropertyNames (native)
    at cloneCallSite (C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:301:10)
    at wrapCallSite (C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:328:13)
    at C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:358:26
    at Array.map (native)
    at Function.prepareStackTrace (C:\Users\lee\AppData\Roaming\npm\node_modules\protractor\node_modules\source-map-support\source-map-support.js:357:24)
    at D:\src\thin-monitor2\node_modules\log4js\lib\layouts.js:30:40
    at Array.map (native)
    at wrapErrorsWithInspect (D:\src\thin-monitor2\node_modules\log4js\lib\layouts.js:29:16)
    at formatLogData (D:\src\thin-monitor2\node_modules\log4js\lib\layouts.js:40:34)
```

**Comment by stanleyxu2005** [comment] 2017-01-11 14:35
use `fileSync` appender instead

**Comment by mgendre** [comment] 2017-02-20 16:38
We also have the same problem when our server ends with an uncaught exception.
This problem is present with the version 1.1.0.

Our code looks like:

```
function exitFailure(error) {
	...
    log4js.shutdown(function() { process.exit(1); });
}

process.on('uncaughtException', function(error) {
    exitFailure(new Error('Uncaught exception'));
});
```

With the 1.1.0, the logs are not written and the error "write after end" is written in the console.

We use a `file` appender. For performance, we don't want to use fileSync appender.


With the release 1.0.1, the problem disappear and the logs are written in the files.

Any suggestions or incoming bugfix ?

**Comment by stanleyxu2005** [comment] 2017-06-11 06:44
@leegee I previously had same issue, but i realized I didn't shutdown my app properly, which is the root cause. You might check, whether your app can shutdown before `process.on('exit')` is called.

**Comment by nomiddlename** [comment] 2017-07-08 03:30
A few causes of the "write after end" problem were fixed in version 2.x. Please re-open if they are still occurring.

**Closed by nomiddlename** 2017-07-08 03:30 UTC

**Comment by DipjayDatta** [comment] 2018-09-25 13:32
[https://github.com/log4js-node/log4js-node/issues/788](url)

**Comment by DipjayDatta** [comment] 2018-09-25 13:33
shutdown have still issues. kindly see #788
