### ISSUE TITLE
Output to multiple files dynamically

### ISSUE THREAD

**Issue by rijnhard** [nomiddlename/log4js-node#437] opened 2017-02-10 14:41 UTC
So I had a use case where I was creating loggers on the fly (that write to their own files) but I needed them to write to any global settings aswell. 

So using this i managed to clone appenders from one logger to another (to a degree)

```javascript
/**
 * Clones the appenders from one logger to another
 * @param {Logger} fromLogger
 * @param {Logger} toLogger
 */
function copyAppenders(fromLogger, toLogger) {
    const logListeners = fromLogger.listeners('log');

    logListeners.forEach((appender) => {
        toLogger.addListener('log', appender);
    });
}
```

**Comment by nomiddlename** [comment] 2017-07-08 03:12
Closing this as not an issue. Thanks for the tip - but users should note that this won't work in version 2.x onwards (no log listeners).

**Comment by rijnhard** [comment] 2017-07-10 09:50
@nomiddlename will v2 have a way to address the use case?

**Comment by nomiddlename** [comment] 2017-07-10 22:57
It doesn't at the moment. I wanted to avoid dynamically adding anything, really - to keep it simple, with a single point of configuration. If you could explain a bit more about why you want to add appenders on the fly, maybe we can come up with an alternative?

**Comment by rijnhard** [comment] 2017-07-11 12:21
@nomiddlename thats an odd one to be honest, our use case is quite unique. 
But essentially we have a testing application based on mocha (but it's really a whole other animal, administering parameter based behavioural tests), each test case is essentially an entire application behaviour, and because of the sheer number of logs its better to have each test case logged in a separate file. 

Because the testing application has hundreds of large test cases making a new logger manually for each test case now is a bit brutal and limits the flexibility since the tests are parameterized as well.

But we want all of those loggers to behave a certain way, so essentially we have the config defined in one place (a json file) and then we clone its config for the new logger.

I completely understand that this is pretty terrible in most applications but because this is a testing application it really isn't a concern.

**Comment by rijnhard** [comment] 2017-07-11 13:25
ideally all I'd want to do is get a clone of logger and change the category name and file it writes to, dynamically.  

But since that is pretty much magic, i'd settle for anything that could help my use case.

**Comment by nomiddlename** [comment] 2017-07-11 22:16
Re-opening this, and turning it into a feature request.

**Comment by rijnhard** [comment] 2017-07-13 09:20
@nomiddlename I love love love that idea, it's elegant, powerful and easy. 

The only thing is how would the new categories `'test.someTestName'` be tied to the config of the `test` category?

**Comment by nomiddlename** [comment] 2017-07-13 22:40
Categories inherit config from their parents (using the dot in the category name creates a hierarchy).

**Comment by nomiddlename** [comment] 2017-07-13 23:11
Published the multiFile appender to NPM in version 2.1.0 - give it a try, see if it does what you need it to do.

**Closed by nomiddlename** 2017-07-13 23:11 UTC
Labels: feature

**Comment by Bingmang** [comment] 2018-05-09 13:45
It also works:
```js
log4js.configure({
  appenders: {
    tests: { type: 'multiFile', base: 'logs/', property: 'categoryName', extension: '.log' }
  },
  categories: {
    default: { appenders: ['tests'], level: 'debug' }
  }
);
const loggerA = log4js.getLogger('A/B/C/D/E')
loggerA.info('I am in logs/A/B/C/D/E.log')
```
This is also a useful feature, but I found that you did not display in the README.md

:) Nothing, just checking.

you guys are so good~

**Comment by andymel123** [comment] 2019-05-27 19:08
Just adding some infos about a problem I have with this solution at the moment.

It is the perfect solution for a requirement I have:
- my node server executes some complex logic every 5min 
- each execution should write to a new file '/executions/<executionId>.log'
- this can run forever

Unfortunately I don't know how to shutdown the logger when I am done. In file.js the appender adds a listener to the 'SIGHUP' event of 'process' and the only way to remove this listener with the log4js api seems to be the log4js.shutdown method. But this method shuts down all appenders?! 
When I add loggers dynamically I guess I need to shut them down dynamically as well.

The problem is: node.js prints warnings on too many listeners on the same event. Here is the warning including the inner-log4js stacktrace:
 
`(node:17312) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:243:17)
    at process.addListener (events.js:259:10)
    at fileAppender (C:\_daten\_projekte\smart_apart\repos\cockpit\cockpit-tsserver\node_modules\log4js\lib\appenders\file.js:77:11)
    at Object.configure (C:\_daten\_projekte\smart_apart\repos\cockpit\cockpit-tsserver\node_modules\log4js\lib\appenders\file.js:88:10)
    at appender (C:\_daten\_projekte\smart_apart\repos\cockpit\cockpit-tsserver\node_modules\log4js\lib\appenders\multiFile.js:41:29)
...`

For now I listen on new listeners for myself and simply remove them again as a workaround.

Maybe there is a solution not to use the multifile but just the file appender?! Maybe I try that next...

**Comment by nomiddlename** [comment] 2019-05-27 22:35
The [multiFile appender](https://log4js-node.github.io/log4js-node/multiFile.html) has a timeout parameter. If no writes have been sent to a particular file appender after this amount of time the file appender will be shutdown. Would that fix your problem?

**Comment by andymel123** [comment] 2019-05-28 16:09
What happens if I set the timeout too short?

**Comment by nomiddlename** [comment] 2019-05-28 23:30
It'll just create the appender again.

**Comment by kernyden** [comment] 2020-01-24 11:44
import { configure, getLogger } from 'log4js';

//log4js format
const layout = { 
    type: 'pattern', 
    pattern: '[%d] [%p] [%c] [%x{context}] - %m%n', 
    tokens: {
        context: ({ data }) => {
            const { context } = data.pop();
            return context;
        } 
    } 
} 

//log4js types + config
const types = {
    log: { type: 'console' },
    file: (appender) => ({ 
        type: 'file', 
        filename: `../logs/${appender}/${appender}.log`, 
        maxLogSize: 10485760, 
        backups: 3 
    })
};

//active services
const services = [ 
    'console', 
    'promin',  
    'errorHandler', 
    'startInfo', 
    'authpp',
    'issues',
    'timeentry',
    'kanbanboards', 
    'teams', 
    'user', 
    'calendar', 
    'activity', 
    'staff', 
    'tracker', 
    'issuecategory', 
    'salary', 
    'esc', 
    'version', 
    'issuestatus', 
    'projects', 
    'member'
];

//service interface
const appender = ({ ...args }) => ({ layout, ...args });

//add service to category
const category = ( ...appenders ) => ({ appenders, level: 'info' });

//logger interface
const logger = (appender) => getLogger(appender);

//'console.log' or type to 'file'
const type = (type) => {
    const { log, file } = types;
    return type === 'console' ? log : file(type);
}

//common interface for all currents
const config = (appenders, action, options) => 
    appenders
        .reduce((prev, curr) => 
            ({ ...prev, [curr]: action(curr) }), 
            options || {}
        )

//common appender interface
const currentAppender = (current) => appender(type(current)); 

//common category interface
const currentCategory = (current) => category(current);

//common logger interface
const currentLogger = (current) => logger(current);

//filter console service (choosen by default)
const filter = (appenders, exception) => appenders.filter(a => a !== exception);

//configure appenders + categories
configure({
    appenders: config(services, currentAppender),
    categories: config(
        filter(services, 'console'), 
        currentCategory, 
        { default: category('console') }
    )
});

//export all configured services
export default {
    ...config(services, currentLogger)
}
