### ISSUE TITLE
Allow configuration of colors for each level

### ISSUE THREAD

**Issue by vjpr** [nomiddlename/log4js-node#90] opened 2012-08-18 22:33 UTC
1. The config should allow levels to be associated with a color.
2. These colors should then been accessible when creating a custom pattern.

Not sure best way to add colors to patterns though.

**Comment by nomiddlename** [comment] 2017-03-27 20:43
Duplicate of #254 - fix for that should fix this one.

**Comment by stanleyxu2005** [comment] 2017-04-15 13:37
Great to find this issue report. Please consider provide individual colors for log levels and individual colors for categories.

**Comment by nomiddlename** [comment] 2017-07-08 02:46
Released in version 2.0.0

**Closed by nomiddlename** 2017-07-08 02:46 UTC
