### ISSUE TITLE
MaxLogSize cannot working for me

### ISSUE THREAD

**Issue by esala116** [nomiddlename/log4js-node#342] opened 2015-12-31 09:23 UTC
configure:
{
      "type": "categoryFilter",
      "appender": {
        "type": "file",
        "absolute": true,
        "filename": "/var/log/service.log",
        "maxLogSize": 40960000,
        "backups": 30
      }
    }
## but my log files are: someone 78M, someone 44k

-rw-r----- 1 root root 4.2M Dec 31 15:59 service.log
-rw-r----- 1 root root 3.6M Dec 30 17:18 service.log.1
-rw-r----- 1 root root  40M Dec 27 08:19 service.log.10
-rw-r----- 1 root root  40M Dec 27 07:59 service.log.11
-rw-r----- 1 root root  40M Dec 27 05:59 service.log.12
-rw-r----- 1 root root  40M Dec 27 06:04 service.log.13
-rw-r----- 1 root root  40M Dec 27 05:58 service.log.14
-rw-r----- 1 root root  78M Dec 28 11:33 service.log.15
-rw-r----- 1 root root  44K Dec 24 18:08 service.log.16
-rw-r----- 1 root root  58K Dec 24 18:08 service.log.17
-rw-r----- 1 root root  49M Dec 24 17:05 service.log.18
-rw-r----- 1 root root 2.8M Dec 22 06:33 service.log.19
-rw-r----- 1 root root 8.8M Dec 30 17:18 service.log.2
-rw-r----- 1 root root 5.1M Dec 22 06:33 service.log.20
-rw-r----- 1 root root  42M Dec 22 05:52 service.log.21
-rw-r----- 1 root root  65M Dec 18 08:33 service.log.22
-rw-r----- 1 root root  25M Dec 18 08:33 service.log.23
-rw-r----- 1 root root 8.6K Dec 16 19:24 service.log.24
-rw-r----- 1 root root  44M Dec 18 15:25 service.log.25
-rw-r----- 1 root root  15M Dec 15 09:53 service.log.26
-rw-r----- 1 root root  46M Dec 15 08:44 service.log.27
-rw-r----- 1 root root  12M Dec 15 07:45 service.log.28
-rw-r----- 1 root root  40M Dec 15 06:08 service.log.29
-rw-r----- 1 root root  43M Dec 30 17:13 service.log.3
-rw-r----- 1 root root  37M Dec 15 09:53 service.log.30
-rw-r----- 1 root root  56M Dec 28 11:34 service.log.4
-rw-r----- 1 root root 7.1M Dec 27 18:38 service.log.5
-rw-r----- 1 root root  40M Dec 28 04:47 service.log.6
-rw-r----- 1 root root  40M Dec 27 11:59 service.log.7
-rw-r----- 1 root root  40M Dec 27 11:39 service.log.8
-rw-r----- 1 root root  40M Dec 27 08:35 service.log.9

**Comment by malquda1** [comment] 2016-11-21 16:21
Do we have an update on this bug?

**Comment by nomiddlename** [comment] 2017-07-08 03:40
Closing this, as it can be caused by multiple appenders writing to the same file. Lots of ways for this to happen were fixed in version 2.x

**Closed by nomiddlename** 2017-07-08 03:40 UTC
