### ISSUE TITLE
how to custom appender ,but don't put in log4js/lib/appenders  directory 

### ISSUE THREAD

**Issue by xml4cn** [nomiddlename/log4js-node#255] opened 2014-10-29 02:38 UTC
I want cunstom a appender ,let categoryFilter appender support Regex , and can use in log4js.json.
but it must put in log4js/lib/appenders  directory, how can I do ? let it put in my project directory??
log4js.json:
{
    "appenders": [{
        "type": "categoryFilterRex",
        "exclude": "adapter*",
        "appender": {
            "type": "dateFile",
            "filename": "logs/log",
            "pattern": "-yyyy-MM-dd.log",
            "alwaysIncludePattern": true,
            "backups": 10,
            "layout": {
                "type": "pattern",
                "pattern": "%r|%p|%c|%m"
            }
        }
    }],
    "replaceConsole": false,
    "levels": {
        "all": "DEBUG",
        "link-service": "ERROR"
    }
}

my appender file:

var log4js = require('log4js');

function categoryFilterRex (excludes, appender) {
    // if (typeof(excludes) === 'string') excludes = [excludes];
    return function(logEvent) {
        if (excludes.search(logEvent.categoryName) === -1) {
            appender(logEvent);
        }
    };
}

function configure(config) {
    log4js.loadAppender(config.appender.type);
    var appender = log4js.appenderMakers[config.appender.type](config.appender);
    return categoryFilter(config.exclude, appender);
}

exports.appender = categoryFilterRex;
exports.configure = configure;

**Comment by Freyert** [comment] 2015-07-30 15:34
It seems strange that the behaviour of loading a custom appender strays `require`. Why isn't it just a `require` under the covers when I use `log4js.configure(config)`?

**Comment by michaelvashchinsky** [comment] 2016-02-02 11:28
Took me some time to figure out how it can be done and the answers above didn't give actual solution.

So..

1. I have created `customAppender.js` in my project folder.
2. in the code I have loaded the module and then called `json4js.loadAppender()` this way:

```javascript
var customConfig = {}; // our config object
var customAppenderModule = require(__dirname + '.customAppender.js'); // load our module, located locally
json4js.loadAppender('custom', customAppenderModule); // register our appender with json4js as 'custom'
json4s.addAppender(json4js.appenders.custom(customConfig)); // configure our appender
```

Hope it more clear and can help.

**Comment by serkanerbasi** [comment] 2017-01-27 16:45
@michaelvashchinsky it occurs 'Cannot read property 'bind' of undefined'?

**Comment by mickeyvip** [comment] 2017-01-27 16:58
@serkanerbasi, I used this a year ago, so things might have changed.

I don't use it anymore, sorry.

**Comment by nomiddlename** [comment] 2017-07-11 22:26
This will be fixed using `process.cwd` under the hood. The workaround above (using `loadAppender`) will not work with version 2.x. 

(duplicate of #368)

**Comment by nomiddlename** [comment] 2017-07-16 23:02
Pushed to NPM in version 2.2.0

**Closed by nomiddlename** 2017-07-16 23:02 UTC
