### ISSUE TITLE
Error: EMFILE: too many  open files

### ISSUE THREAD

**Issue by jeeinn** [nomiddlename/log4js-node#461] opened 2017-03-26 04:03 UTC
log4js.fileAppender - Writing to file log_file.log, error happened  { Error: EMFILE: too many  open files, open 'log_file.log'

version 1.1.0

i don't no how to solve

**Comment by nomiddlename** [comment] 2017-03-26 20:58
You'll need to give me more information than this. How are you configuring log4js? Have you got a sample of code that reproduces the error?

**Comment by fengxiaochuang** [comment] 2017-04-01 03:25
I also encountered this situation,
I was using the log4js version 1.1.1 and my configuration file is
`
{
  "appenders": [
    {
      "type": "console",
      "category": "console"
    },
    {
      "type": "dateFile",
      "filename": "logs/track",
      "alwaysIncludePattern": true,
      "pattern": "-yyyy-MM-dd.log",
      "category": "tracker"
    },
    {
      "type": "dateFile",
      "filename": "logs/system",
      "alwaysIncludePattern": true,
      "pattern": "-yyyy-MM-dd.log",
      "category": "system"
    }
  ],
  "replaceConsole": false,
  "levels": {
    "console": "ALL",
    "tracker": "ERROR",
    "system": "ERROR"
  }
}
`
I tried using the lsof command to view the information and found a lot of logs/tracker and logs/system records

**Comment by nomiddlename** [comment] 2017-04-02 22:24
I can't reproduce the problem with that config. Can you show me the code that is calling log4js, please? The only thing I can think of that would cause this is if you were calling `configure` lots of times.

**Comment by fengxiaochuang** [comment] 2017-04-02 22:44
You are right, I suddenly realized that I put the code to load the configuration of a function of the listener. thank you very much! I will try again and then feedback the results.

**Comment by nomiddlename** [comment] 2017-07-08 02:59
Assuming user fixed their own problem, closing this one.

**Closed by nomiddlename** 2017-07-08 02:59 UTC
