### ISSUE TITLE
shuld upgrade nodemailer

### ISSUE THREAD

**Issue by yuzhigang33** [nomiddlename/log4js-node#522] opened 2017-08-01 07:39 UTC
`npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/`

**Comment by nomiddlename** [comment] 2017-08-01 22:02
Hi, this is a duplicate of #513. I can't upgrade the version of node mailer until I stop supporting node v4 - the current (non-deprecated) version of node mailer needs at least node v6. You're free to install the newer version of node mailer (it is only an optional dependency), the API looks similar so it should work. If it doesn't work, then please create an issue addressing that with details of the error. Thanks.

**Closed by nomiddlename** 2017-08-01 22:02 UTC
